### ISSUE TITLE
ex) [FEAT] 채팅 메신저에 Redis 도입

### ISSUE THREAD

**Issue by cjaehyuk4zed** [ajou-JSL/Backend#10]
## 🖥️ Descriptions
채팅 메신저에 Redis 도입

## ✅ Todo
- [O] Redis 데이터베이스 구축
- [O] Spring과 Redis 연결
- [x] 채팅 로직 속에서 Redis 도입
- [x] 채팅 연결시 Redis에 기록
- [x] 채팅 종료시 Redis에서 기록 삭제
- [x] 기능 테스트

## ☁️ ETC
 - 내용을 적어주세요
