### ISSUE TITLE
[FEAT] 팀 CRUD 기능 개발

### ISSUE THREAD

**Issue by 2eungwoo** [ajou-JSL/Backend#12]
## 🖥️ Descriptions
 - 사용자는 팀을 생성,수정,삭제 및 가입,탈퇴,추방 할 수 있다.

## ✅ Todo
- [x] failing test code 
- [x] product code : CRUD
   - [x] 진행중
- [x] 기능 고도화
- [x] 테스트환경 서버에 배포

## ☁️ ETC
 - 내용을 적어주세요
