### ISSUE TITLE
ex) [FEAT] 채팅 메신저에 MongoDB Atlas Cloud 도입

### ISSUE THREAD

**Issue by cjaehyuk4zed** [ajou-JSL/Backend#13]
## 🖥️ Descriptions
 - 채팅 메신저에 MongoDB Atlas Cloud 도입

## ✅ Todo
- [x] MongoDB Atlas Cloud 데이터베이스 생성
- [x] 백엔드에서 데이터베이스 연결
- [x] 성공적 연결 테스트

## ☁️ ETC
 - 내용을 적어주세요
