### ISSUE TITLE
ex) [FEAT] 채팅 메신저 JWT 인증 구축

### ISSUE THREAD

**Issue by cjaehyuk4zed** [ajou-JSL/Backend#14]
## 🖥️ Descriptions
 - 채팅 메신저 JWT 인증 구축
 - Moum 플랫폼에서 사용할 JWT 인증 방식과 연결해야 한다
 - 승우님의 JWT 토큰 인증 완료시, 테스트 할 예정

## ✅ Todo
- [ ] 메신저에 Spring Security 추가
- [ ] JWT에서 사용자 정보 읽어오기
- [ ] 사용자 정보를 활용한 채팅 대상 선택하기
- [ ] 전체 흐름 테스틩

## ☁️ ETC
 - 내용을 적어주세요
